### ISSUE TITLE
JSON - Removes space after comma inside strings

### ISSUE THREAD

**Issue by MattiasStorm** [Josee9988/MinifyAllCli#43]
**Describe the bug**
Whenever you minify a JSON document, it removes space after comma inside strings while keeping superfluous spaces in other locations and sometimes keep a new line at the end.

**To Reproduce**
1. Open a JSON document
2. Enter something like:
```javascript
[
  {
    "textStrings": "Welcome, stay a while!"
  },
  {
    "textStrings": "Goodbye, take care!"
  }
]
```
3. Minify and the output becomes:
```javascript
[{ "textStrings":"Welcome,stay a while!"},{ "textStrings":"Goodbye,take care!"}
]
```

**Expected behavior**
Expected output would be:
```javascript
[{"textStrings":"Welcome, stay a while!"},{"textStrings":"Goodbye, take care!"}]
```

**Comment by Josee9988** [comment]
Issue is being transferred from MinifyAll to MinifyAllCli which is the main npm package of MinifyAll (it's core)

**Comment by Josee9988** [comment]
Bug is fixed. But there will be some cases in which there will be left some spaces because regex is not fully able to detect when the spaces are inside a string or not.

So the reliability and security of the minifier is improved but the overall minimization rate may be lowered by some minor spaces inside strings (which is not a super big deal).

Thanks for contributing!
