### ISSUE TITLE
Css values

### ISSUE THREAD

**Issue by miksanno** [Josee9988/MinifyAllCli#49]
Some of my values are not minified correctly.

this one, as example;

`@media screen and (min-width: 1025px) {
  #myid{
    box-shadow: #c9c9c9 20px 20px 60px, #ffffff -20px -20px 60px;
  }
}`

results in

`
{box-shadow:#c9c9c9 20px 20px 60px,#ffffff -20px0px -20px 60px}`

Haven't tried adding all 4 expected values.

**Comment by Josee9988** [comment]
The problem is that after that 20px there is no space between the 0px, right? Only that

**Comment by Josee9988** [comment]
Are you using the latest version? Because yesterday I fixed this exact bug: The space before a `0px`.

**Comment by Josee9988** [comment]
![Screenshot_20200902-091627_Firefox Focus.jpg](https://user-images.githubusercontent.com/38838976/91943517-02700c00-ecfd-11ea-84bf-2f5bd49d76c9.jpg). Indeed the bug still persists and it happens on the latest version. I'll try to figure it out today.

Thanks!!

**Comment by Josee9988** [comment]
I made a workaround, that should work. But I have to deeply check why this was happening.

**Comment by Josee9988** [comment]
[MinifyAllCli](https://github.com/Josee9988/MinifyAllCli) is updated to v1.6.5
[MinifyAll](https://github.com/Josee9988/MinifyAll)(vscode) is updated to 2.4.5
[MinifyAllWeb](https://github.com/Josee9988/MinifyAllweb) is updated to 1.6.5. [Web Page(https://minifyall.jgracia.es)
 
Make sure to download the latest version of the minifier and test if the issue is still happening.

Thanks for contributing!!
