### ISSUE TITLE
Minified file contains a leading space

### ISSUE THREAD

**Issue by dougkozar** [Josee9988/MinifyAllCli#52]
Not a huge deal, but just an FYI that when I minify a CSS file the minified files has a space at the beginning containing an extra/unnecessary character.

**Comment by Josee9988** [comment]
Fixed!

**Comment by Josee9988** [comment]
You can check the new MinifyAll version in the VSCode marketplace store or update the npm package if you are using it as a cli command

**Comment by dougkozar** [comment]
Thanks! Couple FYI's: (1) it works if there is 1 leading zero -- it removes that leading zero perfectly! But when there is more than 1 leading zero in the source CSS it minifies down to a leading zero (still). Not sure if you care about that. (2) I enabled the Hex Color shortener to test it. I have a certain color on my site `#FF4500`. The shortener minified it to `#F40`. I was expecting it not to shorten, but it did. Color is a rather important and a precision setting in the world of web accessibility and color contrast. So I ended up disabling that shortener technique because the `45` should not have been minified to `4`. Other than these very minor items, the extension is perfect and great. I tested it against the extension with many more installs -- "CS & JS Minify" and your extension is clearly more comprehensive and robust! Thanks for publishing it!

**Comment by Josee9988** [comment]
1. I can not take into account much wrong code. I mean, I minify it using regex, I expect a correct code, I can not check if the file ends with 0000000 or random characters, if that is what you are telling me
2. The colour shortener tool may be useful in some scenarios but in web development, it truly isn't. It is an extra feature and it is not enabled by default because in most cases the colour will not be the exact as you wrote. It loses colour precision in 95% of the cases, I know. The user can decide whether to lose colour precision and not show the exact exact colour or gain some bytes.

Thanks for posting out, I really appreciate your feedback :)
